### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [alena-kono/notifications_sprint_1#17]
Нужно немного пояснений:
1. Как у вас реализована админка, где манагеры создают рассылки и отправляют.
2. Как отправить что-то кроме email уведомления, если вдруг потребуется.
3. Сможет ли пользователь получить все свои уведомления списком. Полезная функция, часто делают в личном кабинете.
4. Допускаю, что я пропустил. Но не смог найти какой-либо реализации (REST эндпоинт или gRPC) следующего момента. Другие сервисы кинотеатра будут обращаться к сервису нотификации для того или иного уведомления пользователя.
Вот ситуация: в сервисе UGC появился новый комментарий к рецензии пользователя, и сервис UGC просит сервис нотификации уведомить пользователя об этом событии.

Сейчас, кажется, все как-то появляется в Kafka, а вот как, не понятно.

**Comment by nikitazigman** [comment]
@BigDeepBlue 
Здравствуйте! Большое спасибо за ревью! 

1. Админку мы не сделали, не хватило времени. 
2. Если потребуется отправить что-то кроме email, то будет создан дополнительный сервис, который подпишется на новую очередь rabbitmq. Сервис нотификации будет также ходить в пользователький сервис, выбирать нужный канал связи соотносить его с нужной очередью и exchange и перенаправлять сообщения. Сейчас сервис нотификации умеет общаться с пользователем по двум каналам связи: это email и websockets. 
3. Нет такой функции мы не предусмотрели, в нашем случае эвенты не сохраняются в базу. Но чисто теоретически  большую их часть можно достать будет из сервиса UGC. 
4. Когда в сервисе UGC появится новый комментарий, он запишет сообщение в очередь кафки,от туда ее прочитает сервис нотификации и переложит в очередь rabbit для сервиса websockets тот в свою очередь отправит сообщение пользователю. Сейчас аналогичный поток реализован для лайков. 

Мы не написали связку сторонних сервисов с сервисом нотификации. У нас не хватило на это времени. Наш сервис нотификации слушает очереди из кафки и в теории для сервиса нотификации не так важно кто из сервисов написал в эту очередь.

**Comment by BigDeepBlue** [comment]
LGTM

Но все же по поводу п.4. Размышления :), да и просто к сведению:
Общей очередью кафки мы повышаем связность сервисов. А от этого нужно уходить.
И этим же мы создаем единую точку отказа в виде этой кафки, если упадет, что все встанет.

Если бы мы, как это рекомендуется, обращались к сервису нотификации напрямую то:
- повышаем доступность (не зависим от очереди и ее загруженности)
- повышаем надежность (можно сделать сколько угодно реплик сервиса в k8s и не знать проблем)
- делаем сервисы совершенно самостоятельными (по большому счету взял и отнес в другой проект и там все заработало)
